
-- Update the create_sprint_profile function to change experiment_validated parameter from boolean to text
CREATE OR REPLACE FUNCTION public.create_sprint_profile(
  p_user_id uuid, 
  p_name text, 
  p_email text, 
  p_linkedin_url text, 
  p_cv_url text, 
  p_current_job text, 
  p_company_incorporated boolean, 
  p_received_funding boolean, 
  p_funding_details text, 
  p_has_deck boolean, 
  p_team_status text, 
  p_commercializing_invention boolean, 
  p_university_ip boolean, 
  p_tto_engaged boolean, 
  p_problem_defined boolean, 
  p_customer_engagement text, 
  p_market_known boolean, 
  p_market_gap_reason text, 
  p_funding_amount text, 
  p_has_financial_plan boolean, 
  p_funding_sources text[], 
  p_experiment_validated text, -- Changed from boolean to text
  p_industry_changing_vision boolean, 
  p_is_scientist_engineer boolean, 
  p_job_type text, 
  p_ip_concerns boolean, 
  p_potential_beneficiaries boolean, 
  p_specific_customers boolean, 
  p_customer_evidence boolean, 
  p_competition_research boolean, 
  p_success_vision_1yr boolean, 
  p_success_vision_10yr boolean, 
  p_impact_scale text[], 
  p_prior_accelerators boolean, 
  p_prior_accelerators_details text, 
  p_planned_accelerators boolean, 
  p_planned_accelerators_details text, 
  p_lab_space_needed boolean, 
  p_lab_space_secured boolean, 
  p_lab_space_details text, 
  p_deck_feedback boolean, 
  p_utm_source text, 
  p_utm_medium text, 
  p_utm_campaign text, 
  p_utm_term text, 
  p_utm_content text, 
  p_minimal_success_version text, 
  p_dashboard_access_enabled boolean DEFAULT false, 
  p_ambitious_version text DEFAULT NULL::text
)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
  -- Try to update first
  UPDATE public.sprint_profiles 
  SET 
    name = p_name,
    email = p_email,
    linkedin_url = p_linkedin_url,
    cv_url = COALESCE(p_cv_url, cv_url),
    current_job = p_current_job,
    company_incorporated = p_company_incorporated,
    received_funding = p_received_funding,
    funding_details = p_funding_details,
    has_deck = p_has_deck,
    team_status = p_team_status,
    commercializing_invention = p_commercializing_invention,
    university_ip = p_university_ip,
    tto_engaged = p_tto_engaged,
    problem_defined = p_problem_defined,
    customer_engagement = p_customer_engagement,
    market_known = p_market_known,
    market_gap_reason = p_market_gap_reason,
    funding_amount = p_funding_amount,
    has_financial_plan = p_has_financial_plan,
    funding_sources = p_funding_sources,
    experiment_validated = p_experiment_validated,
    industry_changing_vision = p_industry_changing_vision,
    is_scientist_engineer = p_is_scientist_engineer,
    job_type = p_job_type,
    ip_concerns = p_ip_concerns,
    potential_beneficiaries = p_potential_beneficiaries,
    specific_customers = p_specific_customers,
    customer_evidence = p_customer_evidence,
    competition_research = p_competition_research,
    success_vision_1yr = p_success_vision_1yr,
    success_vision_10yr = p_success_vision_10yr,
    impact_scale = p_impact_scale,
    prior_accelerators = p_prior_accelerators,
    prior_accelerators_details = p_prior_accelerators_details,
    planned_accelerators = p_planned_accelerators,
    planned_accelerators_details = p_planned_accelerators_details,
    lab_space_needed = p_lab_space_needed,
    lab_space_secured = p_lab_space_secured,
    lab_space_details = p_lab_space_details,
    deck_feedback = p_deck_feedback,
    utm_source = p_utm_source,
    utm_medium = p_utm_medium,
    utm_campaign = p_utm_campaign,
    utm_term = p_utm_term,
    utm_content = p_utm_content,
    minimal_success_version = p_minimal_success_version,
    dashboard_access_enabled = p_dashboard_access_enabled,
    ambitious_version = p_ambitious_version,
    updated_at = now()
  WHERE user_id = p_user_id;
  
  -- If no rows were updated, insert a new profile
  IF NOT FOUND THEN
    INSERT INTO public.sprint_profiles (
      user_id,
      name,
      email,
      linkedin_url,
      cv_url,
      current_job,
      company_incorporated,
      received_funding,
      funding_details,
      has_deck,
      team_status,
      commercializing_invention,
      university_ip,
      tto_engaged,
      problem_defined,
      customer_engagement,
      market_known,
      market_gap_reason,
      funding_amount,
      has_financial_plan,
      funding_sources,
      experiment_validated,
      industry_changing_vision,
      is_scientist_engineer,
      job_type,
      ip_concerns,
      potential_beneficiaries,
      specific_customers,
      customer_evidence,
      competition_research,
      success_vision_1yr,
      success_vision_10yr,
      impact_scale,
      prior_accelerators,
      prior_accelerators_details,
      planned_accelerators,
      planned_accelerators_details,
      lab_space_needed,
      lab_space_secured,
      lab_space_details,
      deck_feedback,
      utm_source,
      utm_medium,
      utm_campaign,
      utm_term,
      utm_content,
      minimal_success_version,
      dashboard_access_enabled,
      ambitious_version
    ) VALUES (
      p_user_id,
      p_name,
      p_email,
      p_linkedin_url,
      p_cv_url,
      p_current_job,
      p_company_incorporated,
      p_received_funding,
      p_funding_details,
      p_has_deck,
      p_team_status,
      p_commercializing_invention,
      p_university_ip,
      p_tto_engaged,
      p_problem_defined,
      p_customer_engagement,
      p_market_known,
      p_market_gap_reason,
      p_funding_amount,
      p_has_financial_plan,
      p_funding_sources,
      p_experiment_validated,
      p_industry_changing_vision,
      p_is_scientist_engineer,
      p_job_type,
      p_ip_concerns,
      p_potential_beneficiaries,
      p_specific_customers,
      p_customer_evidence,
      p_competition_research,
      p_success_vision_1yr,
      p_success_vision_10yr,
      p_impact_scale,
      p_prior_accelerators,
      p_prior_accelerators_details,
      p_planned_accelerators,
      p_planned_accelerators_details,
      p_lab_space_needed,
      p_lab_space_secured,
      p_lab_space_details,
      p_deck_feedback,
      p_utm_source,
      p_utm_medium,
      p_utm_campaign,
      p_utm_term,
      p_utm_content,
      p_minimal_success_version,
      p_dashboard_access_enabled,
      p_ambitious_version
    );
  END IF;
END;
$function$
